dori/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.conf import settings

urlpatterns = [
    path('doriadmin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/',include('allauth.urls')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns (
    path('' , include('info.urls', namespace = 'info')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/',include('rosetta.urls'))
    ]

info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
	path('' , views.Index , name='index'),
	path('info/', views.Info.as_view(), name='info'),
	path('dori/<str:drug_slug>/', views.DrugDetail.as_view(), name='maindori_detail'),
	path('results/', views.FilterDrugsView.as_view(), name='search_result'),
	path('category/<str:category_slug>', views.CategoryDrugsView.as_view(), name='category_view'),
]

info/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
	name = models.CharField('Kategoriya nomi', max_length=50)
	nameru = models.CharField("Kategoriya nomi ruscha", max_length=50)
	slug = models.SlugField('*', unique=True, max_length=50)
	image = models.ImageField("rasm",upload_to = 'category_photo/')
	desc = models.TextField('Kategoriya haqida', blank=True, max_length=1500)
	descru = models.TextField('Kategoriya haqida ruscha', blank=True, max_length=1500)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Kategoriya'
		verbose_name_plural = 'Kategoriyalar'

	def get_absolute_url(self):
		return reverse('info:category_view',kwargs={'category_slug':self.slug})

class SubCategory(models.Model):
	name = models.CharField('SubKategoriya nomi', max_length=100)
	nameru = models.CharField('SubKategoriya nomi ruscha', max_length=100)
	slug = models.SlugField('*', unique=True, max_length=10)
	category = models.ManyToManyField(Category)
	image = models.ImageField("rasm",upload_to = 'sub_category_photo/')
	desc = models.TextField('Kategoriya haqida', blank=True, max_length=1500)
	descru = models.TextField('Kategoriya haqida ruscha', blank=True, max_length=1500)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'SubKategoriya'
		verbose_name_plural = 'SubKategoriyalar'

	def get_absolute_url(self):
		return reverse('info:sub_category_view',kwargs={'sub_category_slug':self.slug})

class MainDori(models.Model):
	name = models.CharField('Preparatning savdo nomi ya\'ni nomi:',max_length=500)
	nameru = models.CharField('Ruscha Preparatning savdo nomi ya\'ni nomi ruscha :',max_length=500)
	image = models.ImageField("rasm",upload_to = 'info_photo/')
	slug = models.SlugField('*',unique=True,max_length=50)
	affective_stuff = RichTextField('Ta\'sir etuvchi moddalar:')
	affective_stuffru = RichTextField('Ruscha: Ta\'sir etuvchi moddalar:')
	size_of_drug = RichTextField('Dori shakli:')
	size_of_drugru = RichTextField('Ruscha: Dori shakli:')
	ingredients = RichTextField('Tarkibi:')
	ingredientsru = RichTextField('Ruscha: Tarkibi:')
	describtion = RichTextField('Ta\'rifi:')
	describtionru = RichTextField('Ruscha: Ta\'rifi:')
	what_can_drug_do = RichTextField('Farmakoterapeftik guruhi:')
	what_can_drug_doru = RichTextField('Ruscha: Farmakoterapeftik guruhi:')
	code_atx = models.CharField('Kod ATX:',max_length=50)
	category = models.ForeignKey(Category, verbose_name='Kategoriya', on_delete=models.SET_NULL, null=True)
	subcategory = models.ManyToManyField(SubCategory)
	#### FULL DESCRIBTION Farmakalogik xususiyati ####
	far_desc = RichTextField("Farmakalogik xususiyati:")
	far_descru = RichTextField("Ruscha: Farmakalogik xususiyati:")

	# Qo'llanishi
	using = RichTextField("Qo'llanishi:")
	usingru = RichTextField("Ruscha: Qo'llanishi:")

	# Nojo'ya ta'siri
	bad_side = RichTextField("Nojo'ya ta'siri:")
	bad_sideru = RichTextField("Ruscha: Nojo'ya ta'siri:")

	# Qollash mumkin bolmagan holatlar
	non_use = RichTextField("Qo\'llash mumkin bo'lmagan holatlar:")
	non_useru = RichTextField("Ruscha: Qo\'llash mumkin bo'lmagan holatlar:")

	# Dorilarning ozaro tasiri
	react_drugs = RichTextField("Dorilarning o'zaro ta'siri:")
	react_drugsru = RichTextField("Ruscha: Dorilarning o'zaro ta'siri:")

	# Maxsus korsatmalar
	spec_direct = RichTextField("Maxsus korsatmalar:")
	spec_directru = RichTextField("Ruscha: Maxsus korsatmalar:")

	# Chiqarilish shakli
	prod_drug = RichTextField("Chiqarilish shakli:")
	prod_drugru = RichTextField("Ruscha: Chiqarilish shakli:")

	# Saqlash sharoiti
	keep = RichTextField("Saqlash sharoiti:")
	keepru = RichTextField("Ruscha: Saqlash sharoiti:")

	# Yaroqlilik muddati
	shelf_life = RichTextField("Yaroqlilik muddati:")
	shelf_liferu = RichTextField("Ruscha: Yaroqlilik muddati:")

	# Dorixonalarda berilish tartibi
	give = RichTextField("Dorixonalarda berilish tartibi:")
	giveru = RichTextField("Ruscha: Dorixonalarda berilish tartibi:")

	# Ishlab chiqaruvchi
	producer = RichTextField("Ishlab chiqaruvchi:")
	producerru = RichTextField("Ruscha: Ishlab chiqaruvchi:")
	date = models.DateTimeField('post sanasi', auto_now_add=True)

	class Meta:
		verbose_name = 'Dori'
		verbose_name_plural = 'Dorilar'

	def __str__(self):
		return self.name

	def get_dori(self):
		return reverse('info:maindori_detail', kwargs={'drug_slug':self.slug})


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateField(auto_now_add=True)
	post = models.ForeignKey('MainDori',on_delete=models.CASCADE)
	content = models.TextField()

	def __str__(self):
		return slef.user.username

info/forms.py
from django import forms
from .models import Comment
 
class CommentForm(forms.ModelForm):
    content = forms.CharField(label ="", widget = forms.Textarea(
    attrs ={
        'class':'form-control',
        'placeholder':'Comments',
        'rows':4,
        'cols':50
    }))
    class Meta:
        model = Comment
        fields =['content']

info/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse,JsonResponse
from .models import *
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.utils.translation import gettext as _
from django.utils.translation import get_language,activate,gettext
from django.views.generic.base import View
from .forms import CommentForm
from django.views.generic import ListView,DetailView
from django.db.models import Q
from django.core.paginator import Paginator
cur_language = get_language()
# Create your views here.
def Index(request):
	category = Category.objects.all()
	dori = MainDori.objects.all().order_by('-date')[:8]

	context = {
	'cat':category,
	'dori':dori,
	}

	return render(request,"index.html",context)


class Info(View):
	def get(self, request):
		dori = MainDori.objects.all().order_by('date')
		category = Category.objects.all()

		paginator = Paginator(dori, 4) # Show 2 movies per page.
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)

		context = {
		'dori':dori,
		'cat':category,
		}
		return render(request, 'blog-grid.html',context)

class DrugDetail(View):
	def get(self, request, drug_slug):

		drug = get_object_or_404(MainDori,slug=drug_slug)
		category = Category.objects.all()

		context = {
		'dori':drug,
		'cat':category,

		}
		return render(request, 'blog-single.html', context)


class FilterDrugsView(ListView):
	#Filter inDori
	model = MainDori
	template_name = 'list.html'
	
	def get_queryset(self): # new 
		query = self.request.GET.get('q')
		object_list = MainDori.objects.filter(
			Q(name__icontains=query) | Q(nameru__icontains=query)| Q(describtion__icontains=query)| Q(describtionru__icontains=query)
		)

		return object_list

class CategoryDrugsView(ListView):
	# Category Movies View
	def get(self, request, category_slug):
		category = Category.objects.get(slug=category_slug)
		drugs = category.maindori_set.all()

		paginator = Paginator(drugs, 4) # Show 2 movies per page.
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)

		context = {'category_drug':drugs, 'drugs':page_obj}
		return render(request, 'categories_list.html', context)

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>{% trans "Dori - Dorilar haqida barcha ma'lumot" %}</title>
    <meta name="author" content="Nile-Theme">
    <meta name="robots" content="index follow">
    <meta name="googlebot" content="index follow">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="keywords" content="dori , info , doriinfo , o'g'riq qoldiruvchi">
    <meta name="description" content="Dori - Dorilar haqida ma'lumot">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800%7CPoppins:300i,300,400,700,400i,500%7CDancing+Script:700%7CDancing+Script:700" rel="stylesheet">
    <!-- animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
    <!-- owl Carousel assets -->
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- hover anmation -->
    <link rel="stylesheet" href="{% static 'css/hover-min.css' %}">
    <!-- flag icon -->
    <link rel="stylesheet" href="{% static 'css/flag-icon.min.css' %}">
    <!-- main style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- colors -->
    <link rel="stylesheet" href="{% static 'css/colors/main.css' %}">
    <!-- elegant icon -->
    <link rel="stylesheet" href="{% static 'css/elegant_icon.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <!-- jquery library  -->
    <script  src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <!-- fontawesome  -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>



</head>

<body>

    <header>
        <div id="fixed-header-dark" class="header-output fixed-header" style="background-color: #007CFF !important;">
            <div class="container header-in">

                <div class="row">
                    <div class="col-lg-1 col-md-12 img-fluid">
                        <a id="logo" href="{% url 'info:index' %}" class="d-inline-block margin-tb-10px img-fluid"style="background-color: #CCCCCC !important; width: 50px; height: 50px; border-radius: 10px;"><img src="{% static 'img/drug.svg' %}" alt="" class="img-fluid rounded"></a>
                        <a class="mobile-toggle padding-13px background-main-color"  style="border-radius:10px;"><i class="fas fa-bars" style="border-radius:20px;"></i></a>
                    </div>
                    <div class="col-lg-9 col-md-12 position-inherit" >
                        <ul id="menu-main" class="nav-menu float-lg-left ml-lg-5 link-padding-tb-20px" >
                            <li class=""><a href="{% url 'info:index' %}" style="color:#FFFFFF; opacity: 1; font-size:150% ;">{% trans 'Bosh sahifa' %}</a></li>


                            <li ><a href="{% url 'info:info' %}" style="color:#FFFFFF; opacity: 1; font-size:150% ;">{% trans 'Dorilar' %}</a>
                            </li>

                        </ul>
                    </div>

                    <div class="col-lg-2 col-md-12 position-inherit pt-lg-3">

                        <ul id="menu-main" class="nav-menu float-lg-right link-padding-tb-20px">
                            <li class="">
                                <form action="{% url 'set_language' %}" method="POST" style="">
                                    <div class="" >
                                                {% csrf_token %}
                                        <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}" />

                                        <select class="selectpicker sariq" name="language" style="background-color: #007CFF; border-radius:5px; padding-right: 21px; border-color: white; padding: 6px; font-size: 150%;" onchange="this.form.submit()" >
                                              {% get_current_language as LANGUAGE_CODE %}
                                              {% get_available_languages as LANGUAGES %}
                                              {% get_language_info_list for LANGUAGES as languages %}
                                              {% for language in languages %}
                                              <option
                                                value="{{language.code}}"
                                                {% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                                <span>{{language.code}}</span>
                                              </option>
                                                {% endfor %}
                                        </select>
                                    </div>
                                </form>                        
                            </li>

                        </ul>

                            
                        </div>
                                    
                    </div>
                </div>

            </div>
        </div>
    </header>

    <!-- // Header  -->

    {% block content %}
    {% endblock %}

        <footer class="padding-tb-50px background-main-color wow fadeInUp">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="margin-0px text-white opacity-7 sm-mb-15px" style="font-size:150%;">© 2022  <span class="pl-3"></span> {% trans "Dori - Dorilar haqida barcha ma'lumot" %}<span class="pl-3"></span> |<span class="pl-3"></span> {% trans "Barcha huquqlar himoyalangan" %}</p>
                </div>
                <!--
                <div class="col-lg-6">
                    <ul class="social-icon style-2 float-lg-right">
                        <li class="list-inline-item"><a class="facebook" href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a class="youtube" href="#"><i class="fab fa-youtube"></i></a></li>
                        <li class="list-inline-item"><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
                        <li class="list-inline-item"><a class="google" href="#"><i class="fab fa-google-plus"></i></a></li>
                        <li class="list-inline-item"><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
                        <li class="list-inline-item"><a class="rss" href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
                    </ul>
                </div> -->
            </div>
        </div>
    </footer>
    <script  src="{% static 'js/sticky-sidebar.js' %}"></script>
    <script  src="{% static 'js/YouTubePopUp.jquery.js' %}"></script>
    <script  src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script  src="{% static 'js/imagesloaded.min.js' %}"></script>
    <script  src="{% static 'js/wow.min.js' %}"></script>
    <script  src="{% static 'js/custom.js' %}"></script>
    <script  src="{% static 'js/popper.min.js' %}"></script>
    <script  src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/blog-grid.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <!-- // Header  -->
{% get_current_language as LANGUAGE_CODE %}
<div class="padding-tb-30px"></div>


    <div class="margin-tb-30px">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        {% for d in dori %}
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="{{d.get_dori}}"><img src="{{d.image.url}}" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="{{d.category.get_absolute_url}}" class="text-main-color" style="font-size: 18px;">
                                    {% if LANGUAGE_CODE == 'uz' %}
                                {{d.category.name}} 
                                {% else %}
                                {{d.category.nameru}} 
                                {% endif %}
                            </a>
                                <h1><a href="{{d.get_dori}}" class="d-block text-dark text-capitalize  margin-tb-15px">
                                    {% if LANGUAGE_CODE == 'uz' %}
                                {{d.name}} {% else %} {{d.nameru}} {% endif %}</a></h1>
                                <span class="text-extra-small" style="font-size:16px;"><i class="far fa-clock text-grey-2" ></i>{% trans 'Qoyildi : ' %}  <a href="{{d.get_dori}}" style="font-size:13px;">{{d.date}}</a></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <ul class="pagination pagination-md ">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">{% trans 'Oldingi' %}</a></li>
                        {% else %}
                        {% endif %}
                        {% if page_obj.number > 1 %}
                        <li class="page-item">
                            {{ page_obj.number }} - {% trans 'sahifa,' %}  {{ page_obj.paginator.num_pages }} {% trans 'dan.' %}'
                        </li>
                        {% else %}
                        {% endif %}
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}">{% trans 'Keyingi' %}</a></li>
                        {% else %}
                        
                        {% endif %}
                    </ul>

                </div>
                <div class="col-lg-4">

                    <div class="margin-bottom-30px">
                        <div class="padding-30px background-white border-radius-10">
                            <h4><i class="fas fa-search margin-right-10px text-main-color"></i>{% trans 'Qidiruv' %}</h4>
                            <hr>
                            <form method="get" action="{% url 'info:search_result' %}">
                            <div class="input-group mb-3">
                              <input type="text" placeholder="{% trans 'Dori nomi..' %}" class="form-control border-radius-0" name="q">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary text-white background-main-color border-radius-0" type="submit">{% trans 'Izlash' %}</button>
                                </div>
                            </div>
                            </form>

                        </div>
                    </div>

                    <div class="widget widget_categories">
                        <div class="margin-bottom-30px">
                            <div class="padding-30px background-white border-radius-10">
                                <h4><i class="far fa-folder-open margin-right-10px text-main-color"></i> {% trans 'Kategoriyalar' %}</h4>
                                <hr>
                                <ul>
                                    {% for c in cat %}
                                    {% if LANGUAGE_CODE == 'uz' %}
                                    <li><a href="{{c.get_absolute_url}}">{{c.name}}</a></li>
                                    {% else %}
                                    <li><a href="{{c.get_absolute_url}}">{{c.nameru}}</a></li>
                                    {% endif %}
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                    </div>



                </div>
            </div>

        </div>
    </div>


{% endblock %}

templates/categories_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <!-- // Header  -->
{% get_current_language as LANGUAGE_CODE %}



    <div class="margin-tb-30px">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mt-lg-5">
                    <h1 class="mb-5 mt-lg-5" style="font-size:50px;">
                        {% for drugs in page_obj|slice:"1" %}
                        {% if LANGUAGE_CODE == 'uz' %} {{drugs.category.name}}  
                        {% else %}{{drugs.category.nameru}} {% endif %}
                        {% trans 'Dorilar' %}
                        {% endfor %}</h1>
                    <div class="row">
                        {% if drugs %}
                        {% for d in drugs %}
                        <div class="col-lg-6 margin-bottom-40px">
                            <div class="thum"><a href="{{d.get_dori}}"><img src="{{d.image.url}}" alt=""></a></div>
                            <div class="padding-30px background-white">
                                <i class="far fa-folder-open text-main-color"></i>
                                <a href="{{d.category.get_absolute_url}}" class="text-main-color" style="font-size: 18px;">
                                {% if LANGUAGE_CODE == 'uz' %}
                                {{d.category}} 
                                {% else %}
                                {{d.category.nameru}} 
                                {% endif %}
                            </a>
                                <h1><a href="{{d.get_dori}}" class="d-block text-dark text-capitalize  margin-tb-15px">{% if LANGUAGE_CODE == 'uz' %}
                                {{d.name}} {% else %} {{d.nameru}} {% endif %}</a></h1>
                                <span class="text-extra-small" style="font-size:16px;"><i class="far fa-clock text-grey-2" ></i>{% trans 'Qoyildi : ' %}  <a href="{{d.get_dori}}" style="font-size:13px;">{{d.date}}</a></span>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <br>
                        <h2 class="" style="color:red;">{% trans "Hozircha bu katoriyaga oid dorilar yo'q" %}</h2>
                        {% endif %}
                    </div>

                    <ul class="pagination pagination-md ">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">{% trans 'Oldingi' %}</a></li>
                        {% else %}
                        {% endif %}
                        {% if page_obj.number > 1 %}
                        <li class="page-item">
                            {{ page_obj.number }} - {% trans 'sahifa,' %}  {{ page_obj.paginator.num_pages }} {% trans 'dan.' %}'
                        </li>
                        {% else %}
                        {% endif %}
                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}">{% trans 'Keyingi' %}</a></li>
                        {% else %}
                        
                        {% endif %}
                    </ul>

                </div>
                <div class="col-lg-4 mt-lg-5">

                    <div class="margin-bottom-30px mt-lg-5">
                        <div class="padding-30px background-white border-radius-10">
                            <h4><i class="fas fa-search margin-right-10px text-main-color"></i> {% trans 'Qidiruv' %}</h4>
                            <hr>
                            <form action="{% url 'info:search_result' %}" method="get">
                            <div class="input-group mb-3">
                              <input type="text" placeholder="{% trans 'Dori nomi..' %}" class="form-control border-radius-0" name="q">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary text-white background-main-color border-radius-0" type="submit">{% trans 'Izlash' %}</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>

                    <div class="widget widget_categories">
                        <div class="margin-bottom-30px">
                            <div class="padding-30px background-white border-radius-10">
                                <h4><i class="far fa-folder-open margin-right-10px text-main-color"></i> {% trans 'Kategoriyalar' %}</h4>
                                <hr>
                                <ul>
                                    {% for c in cat %}
                                    {% if LANGUAGE_CODE == 'uz' %}
                                    <li><a href="{{c.get_absolute_url}}">{{c.name}}</a></li>
                                    {% else %}
                                    <li><a href="{{c.get_absolute_url}}">{{c.nameru}}</a></li>
                                    {% endif %}
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                    </div>



                </div>
            </div>

        </div>
    </div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

    <section class="banner padding-tb-200px sm-ptb-80px background-overlay">
        <div class="container z-index-2 position-relative">
            <div class="title">
                <h1 class="text-title-large text-main-color font-weight-300 margin-bottom-15px" style="font-size:650% ;">Dori Info</h1>
                <h4 class="font-weight-300 text-main-color text-up-small" style="font-size:250% ;">{% trans "Dorilar haqidagi barcha ma'lumot" %}</h4>
            </div>
            <div class="row margin-tb-60px">
                <div class="col-lg-8">
                    <div class="listing-search">
                        <form class="row no-gutters" method="get" action="{% url 'info:search_result' %}">
                            <div class="col-md-9">
                                <div class="keywords">
                                    <input class="listing-form first" type="text" placeholder="{% trans 'Dori nomi' %}" value="" name="q" style="font-size:150% ;">
                                </div>
                            </div>

                            <div class="col-md-3">
                                <button class="listing-bottom background-second-color box-shadow" style="border-color: transparent; font-size: 150%;" >{% trans 'Izlash' %}
                                </button>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        {% for cat in cat %}
                        <div class="col-md-3 col-6 sm-mb-30px wow fadeInUp padding-tb-15px">
                            <a href="{{cat.get_absolute_url}}" class="d-block border-radius-15 hvr-float hvr-sh2">
                                <div class="background-main-color text-white border-radius-15 padding-20px text-center opacity-hover-10" style="font-size:150% ;">
                                    <div class="icon margin-bottom-15px opacity-7 rounded">
                                        <img src="{{cat.image.url}}" alt="" style="border-radius:10px;">
                                    </div>
                                    {{cat.name}}
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>





    <section class="padding-tb-100px background-grey-1">
        <div class="container">
            <!-- Title -->
            <div class="row justify-content-center margin-bottom-45px">
                <div class="col-lg-10">
                    <div class="row">
                        <div class="col-md-4 wow fadeInUp">
                            <h1 class="text-second-color font-weight-300 text-sm-center text-lg-right margin-tb-15px" style="font-size:350%;">{% trans "Dorilar" %}</h1>
                        </div>
                        <div class="col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                            <p class="text-grey-2 margin-tb-10px" style="font-size:150%;">{% trans "Dorilar haqidagi barcha ma'lumotlar shu yerda, kerakli dorini ustiga bosib u haqidagi ma'lumotni bilib oling" %}</p>
                        </div>
                        <div class="col-md-2 wow fadeInUp" data-wow-delay="0.4s">
                            <a href="{% url 'info:info' %}" class="text-main-color margin-tb-15px d-inline-block"><span class="d-block float-left margin-right-10px margin-top-5px" style="font-size:100%;">{% trans "Hamma dorilar" %}</span> <i class="far fa-arrow-alt-circle-right text-large margin-top-7px"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- // Title -->

            <div class="row">

                <!-- Dori -->
                {% for d in dori %}
                <div class="col-lg-3 col-md-6 hvr-bob sm-mb-45px">
                    <div class="background-white box-shadow wow fadeInUp" data-wow-delay="0.2s">
                        <div class="thum">
                            <a href="{{d.get_dori}}"><img src="{{d.image.url}}" alt=""></a>
                        </div>
                        <div class="padding-30px">
                            <h2 class="margin-tb-15px"><a class="text-dark" href="{{d.get_dori}}">{{d.name}}</a></h2>

                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- // Dori -->



            </div>
        </div>
    </section>



{% endblock %}